# Generated by Django 5.2.15 on 2026-08-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('INR', 'INR'), ('AED', 'AED'), ('SAR', 'SAR'), ('PKR', 'PKR'), ('CNY', 'CNY'), ('TRY', 'TRY'), ('BRL', 'BRL'), ('KRW', 'KRW'), ('NGN', 'NGN'), ('ZAR', 'ZAR'), ('EGP', 'EGP'), ('THB', 'THB'), ('MYR', 'MYR'), ('IDR', 'IDR'), ('PHP', 'PHP'), ('VND', 'VND'), ('KWD', 'KWD'), ('QAR', 'QAR'), ('BHD', 'BHD'), ('OMR', 'OMR'), ('JOD', 'JOD'), ('LBP', 'LBP'), ('IQD', 'IQD'), ('MAD', 'MAD'), ('TND', 'TND'), ('KES', 'KES'), ('GHS', 'GHS'), ('TZS', 'TZS'), ('UGX', 'UGX'), ('ETB', 'ETB'), ('XOF', 'XOF'), ('RUB', 'RUB'), ('UAH', 'UAH'), ('PLN', 'PLN'), ('SEK', 'SEK'), ('NOK', 'NOK'), ('DKK', 'DKK'), ('CHF', 'CHF'), ('NZD', 'NZD'), ('HKD', 'HKD'), ('SGD', 'SGD'), ('TWD', 'TWD'), ('MUR', 'MUR'), ('BDT', 'BDT'), ('LKR', 'LKR'), ('NPR', 'NPR'), ('AFN', 'AFN'), ('MMK', 'MMK'), ('KHR', 'KHR'), ('LAK', 'LAK'), ('MNT', 'MNT'), ('GEL', 'GEL'), ('AMD', 'AMD'), ('AZN', 'AZN'), ('KZT', 'KZT'), ('UZS', 'UZS'), ('TJS', 'TJS'), ('KGS', 'KGS'), ('TMT', 'TMT'), ('BYN', 'BYN'), ('MDA', 'MDA'), ('ALL', 'ALL'), ('BAM', 'BAM'), ('MKD', 'MKD'), ('RSD', 'RSD'), ('HRK', 'HRK'), ('BGN', 'BGN'), ('ISK', 'ISK'), ('HUF', 'HUF'), ('CZK', 'CZK'), ('MDL', 'MDL'), ('GMD', 'GMD'), ('SLL', 'SLL'), ('LRD', 'LRD'), ('CDF', 'CDF'), ('BIF', 'BIF'), ('RWF', 'RWF'), ('MWK', 'MWK'), ('ZMW', 'ZMW'), ('SZL', 'SZL'), ('LSL', 'LSL'), ('NAD', 'NAD'), ('BWP', 'BWP'), ('MZN', 'MZN'), ('AOA', 'AOA'), ('MGA', 'MGA'), ('SCR', 'SCR'), ('MVR', 'MVR'), ('BTN', 'BTN'), ('BND', 'BND'), ('XPF', 'XPF'), ('TOP', 'TOP'), ('WST', 'WST'), ('FJD', 'FJD'), ('PGK', 'PGK'), ('SBD', 'SBD'), ('VUV', 'VUV')], default='USD', max_length=3),
        ),
    ]
